#!/usr/bin/bash

sbcl --script cl.lisp > c.c         &&
gcc c.c -o c && ./c   > js.js       &&
node js.js            > php.php     &&
php php.php           > perl-5.pl   &&
perl perl-5.pl        > ruby-3.rb   &&
ruby ruby-3.rb        > python-3.py &&
python python-3.py    > out.lisp    &&
cmp cl.lisp out.lisp
